### Homework Numpy 1

check if numpy is installed

In [82]:
!pip list -v

Package                         Version          Location                                  Installer
------------------------------- ---------------- ----------------------------------------- ---------
aext-assistant                  4.1.0            c:\users\user\anaconda3\lib\site-packages conda
aext-assistant-server           4.1.0            c:\users\user\anaconda3\lib\site-packages conda
aext-core                       4.1.0            c:\users\user\anaconda3\lib\site-packages conda
aext-core-server                4.1.0            c:\users\user\anaconda3\lib\site-packages conda
aext-panels                     4.1.0            c:\users\user\anaconda3\lib\site-packages conda
aext-panels-server              4.1.0            c:\users\user\anaconda3\lib\site-packages conda
aext-project-filebrowser-server 4.1.0            c:\users\user\anaconda3\lib\site-packages conda
aext-share-notebook             4.1.0            c:\users\user\anaconda3\lib\site-packages conda
aext-share-notebook-se

import numpy

In [86]:
import numpy as np

**EX 1**
arange practice

In [89]:
print(np.arange(1,11))
print(np.arange(0.5,5.25,0.25))

[ 1  2  3  4  5  6  7  8  9 10]
[0.5  0.75 1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25 3.5  3.75
 4.   4.25 4.5  4.75 5.  ]


**EX 2**
zeros practice

In [92]:
print(np.zeros(10,dtype=int))
print(np.zeros((3,4),dtype=int))

[0 0 0 0 0 0 0 0 0 0]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


**EX 3**
linspace practice

In [95]:
print(np.linspace(2,12,5,dtype=int))
print(np.linspace(3,9,4,dtype=int))

[ 2  4  7  9 12]
[3 5 7 9]


**EX 4**
random.rand + random.randint practice

In [98]:
randy1 = np.random.rand(4,2)
randy2 = np.random.randint(10,20,(3,3))
print(randy1)
print(randy2)
np.reshape(randy1, (1,8))
# Before using reshape we have to make sure the output array will have the same amount of cells as the input array

[[0.84708259 0.95300081]
 [0.00257983 0.91781625]
 [0.82374401 0.55153581]
 [0.73692883 0.93629022]]
[[11 12 15]
 [12 14 11]
 [12 14 12]]


array([[0.84708259, 0.95300081, 0.00257983, 0.91781625, 0.82374401,
        0.55153581, 0.73692883, 0.93629022]])

**EX 5**
seed function and usage

In [101]:
# If we use a fixed seed the random generated numbers will always be the same
# Seed allaws better predictability and repeatability when necessary