## Homework Numpy 2

check if numpy is installed

In [82]:
!pip list -v

Package                         Version          Location                                  Installer
------------------------------- ---------------- ----------------------------------------- ---------
aext-assistant                  4.1.0            c:\users\user\anaconda3\lib\site-packages conda
aext-assistant-server           4.1.0            c:\users\user\anaconda3\lib\site-packages conda
aext-core                       4.1.0            c:\users\user\anaconda3\lib\site-packages conda
aext-core-server                4.1.0            c:\users\user\anaconda3\lib\site-packages conda
aext-panels                     4.1.0            c:\users\user\anaconda3\lib\site-packages conda
aext-panels-server              4.1.0            c:\users\user\anaconda3\lib\site-packages conda
aext-project-filebrowser-server 4.1.0            c:\users\user\anaconda3\lib\site-packages conda
aext-share-notebook             4.1.0            c:\users\user\anaconda3\lib\site-packages conda
aext-share-notebook-se

import numpy

In [84]:
import numpy as np

**EX 1**
Creating and reshaping arrays

In [88]:
randy = np.arange(1,17)
np.reshape(randy, (4,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

**EX 2**
Using arrange and reshape

In [91]:
randy1 = np.arange(10,50,5)
print(np.reshape(randy1, (2,4)))

[[10 15 20 25]
 [30 35 40 45]]


**EX 3**
Randint practice

In [94]:
randy2 = np.random.randint(1, 100, (3,3))
print(randy2)
print(randy2.max(), randy2.min())

[[77 63 60]
 [25 60 81]
 [14 43 71]]
81 14


**EX 4**
Slicing practice

In [97]:
randy3 = np.random.randint(0, 21, size=10)
print(randy3)
print(randy3[:5])
print(randy3[::2])
print(randy3[::-1])

[ 3  4 13 18  4 17 13  6  6 18]
[ 3  4 13 18  4]
[ 3 13  4 13  6]
[18  6  6 13 17  4 18 13  4  3]


**EX 5**
Slicing 2D array

In [100]:
randy4 = np.random.randint(1, 51, size=(4, 5))
print(randy4)
print(randy4[1])
print(randy4[:, 3])

[[50 36 49 20  8]
 [11 21 22 12 32]
 [22 42  1  2 49]
 [40 44 12 12 25]]
[11 21 22 12 32]
[20 12  2 12]


**EX 6**
Using argmax and argmin

In [103]:
randy5 = np.random.randint(0, 101, 15)
print(randy5)
print(np.argmax(randy5), np.argmin(randy5))
print(randy5[randy5 % 5 == 0])
print(randy5[(randy5 < 10) | (randy5 > 50)])

[ 2 81 74 61 36 72 97 77 99 74 76 87 14 43 29]
8 0
[]
[ 2 81 74 61 72 97 77 99 74 76 87]
