## Homework Numpy 3

import numpy, pandas ,display and pyplot

In [1]:
import numpy as np
import pandas as pd
from IPython.display import display
import matplotlib.pyplot as plt

**EX 1**
NUMPY exercise

In [4]:
np.random.seed(80)
randy = np.random.randint(1, 100, (4,4))
print(randy)

# a
print("print numbers above 50",randy[randy>50])

# b
print("print columns sums",randy.sum(axis = 0))
print("print rows sums",randy.sum(axis = 1))

# c
print("print columns max",np.max(randy, axis = 0))
print("print rows max",np.max(randy, axis = 1))
print("print columns min",np.min(randy, axis = 0))
print("print rows min",np.min(randy, axis = 1))
print("print columns avg",np.mean(randy, axis = 0))
print("print rows avg",np.mean(randy, axis = 1))

[[48 61 39 84]
 [11 51  4 87]
 [24 16 82  6]
 [65 10 93 43]]
print numbers above 50 [61 84 51 87 82 65 93]
print columns sums [148 138 218 220]
print rows sums [232 153 128 211]
print columns max [65 61 93 87]
print rows max [84 87 82 93]
print columns min [11 10  4  6]
print rows min [39  4  6 10]
print columns avg [37.  34.5 54.5 55. ]
print rows avg [58.   38.25 32.   52.75]


**EX 2**
PANDAS exercise

In [7]:
new_games = {
"Final Fantasy VII Rebirth": 69.99,
"Astro Bot": 59.99,
"Star Wars Outlaws": 69.99,
"Silent Hill 2 Remake": 69.99,
"Elden Ring: Shadow of the Erdtree": 39.99,
"Dragon Age: The Veilguard": 69.99,
"Metaphor: ReFantazio": 59.99
}

new_games_series = pd.Series(new_games)
print(new_games_series)

# a
print("Metaphor: ReFantazio : ", new_games_series['Metaphor: ReFantazio'])

# b
print("Keys: ", new_games_series.keys())

# c
print("price of index 3: ", new_games_series.iloc[3])

# d
print("sum price of all games: ", np.sum(new_games_series.values))

Final Fantasy VII Rebirth            69.99
Astro Bot                            59.99
Star Wars Outlaws                    69.99
Silent Hill 2 Remake                 69.99
Elden Ring: Shadow of the Erdtree    39.99
Dragon Age: The Veilguard            69.99
Metaphor: ReFantazio                 59.99
dtype: float64
Metaphor: ReFantazio :  59.99
Keys:  Index(['Final Fantasy VII Rebirth', 'Astro Bot', 'Star Wars Outlaws',
       'Silent Hill 2 Remake', 'Elden Ring: Shadow of the Erdtree',
       'Dragon Age: The Veilguard', 'Metaphor: ReFantazio'],
      dtype='object')
price of index 3:  69.99
sum price of all games:  439.93
